### ISSUE TITLE
Release new octomap_server

### ISSUE THREAD

**Issue by jvgomez** [ros-gbp/octomap_mapping-release#1]
Hi,

I am not very familiar on how the release procedure works, but I see that the [last Indigo-trusty release](https://github.com/ros-gbp/octomap_mapping-release/commits/debian/ros-indigo-octomap-server_0.5.3-0_trusty) is more than one year old, but in the [octomap_mapping repo](https://github.com/OctoMap/octomap_mapping/commits/indigo-devel) there have been some commits specially during last months.

Is there any plan to update the release? Thank you.

**Comment by ahornung** [comment]
I intend not update the indigo release anymore, unless there are important fixes outstanding. There shouldn't be any API changes or similar at this point in time. 

Is there a certain commit or feature you miss?

**Comment by jvgomez** [comment]
I was wondering whether the contributions I did (which were just to include more parameters to the dynamic reconfigure server) were going to be included in the release so that I can depend on the debian instead of on the code. There should not be any API change but I completely understand your point :)

**Comment by jack-oquin** [comment]
FWIW, I agree completely with @ahornung as a general maintenance policy.

But, because Indigo is slated for long-term support, I've been making exceptions in some packages I personally maintain for useful extensions that are backwards compatible and can reasonably be expected not to affect existing users. That comes down to a guess as to the risks and benefits of each individual change.

**Comment by ahornung** [comment]
Looking at the diff (https://github.com/OctoMap/octomap_mapping/compare/0.5.3...indigo-devel?diff=split&name=indigo-devel&short_path=04c6e90), then this could indeed be viable, especially considering the long-term support of Indigo. There are mostly additions to the ROS interface and the changes to the OctomapServer API are minor.

What I would need before a release is someone to extensively test the `indigo-devel` code, since I don't have the infrastructure nor time at the moment. I'd be happy to fire up a release then.

**Comment by jvgomez** [comment]
@ahornung I have a code in which I run the octomap_server_node with Gazebo simulation. I think I can also test this in a real robot (although it will require some time). Running it for some hours would be OK or do we need to test something else?

**Comment by ahornung** [comment]
@jvgomez I think some simulation runs are sufficient, incrementally building and visualizing a map,  playing with the various options / params / dynamic_reconfigure etc.

**Comment by jvgomez** [comment]
I actually found a small issue when configuring parameters with the reconfigure server. When I try to set the sensor_model_hit to 0.0 the following assertion triggers:

```
octomap_server_node: /opt/ros/indigo/include/octomap/AbstractOccupancyOcTree.h:190: void      octomap::AbstractOccupancyOcTree::setProbHit(double): Assertion `prob_hit_log >= 0.0' failed.
```

I guess it is a matter of double comparison but I do not have the time to look into it in detail. For the rest of the stuff it seems to be working as the current release.

**Comment by ahornung** [comment]
The log-odds values for a hit must be >= 0 and for a miss <= 0. That means that the hit probability `sensor_model_hit` should be >= 0.5 and `sensor_model_miss` should be <= 0.5. This should probably be reflected in dynamic_reconfigure somehow to avoid sudden crashes.

**Comment by jvgomez** [comment]
I see, fixed and now the crash is not happening anymore. What about sensor_model_mix/max, are they bothn within [0,1]?

**Comment by ahornung** [comment]
They are both within [0,1] and there is no hard assertion checking them.

**Comment by jvgomez** [comment]
[This PR](https://github.com/OctoMap/octomap_mapping/pull/27) fixes the assertion. What I just realized is that the other bounds for hit and miss might be wrong as well (ouch!). However, I am not sure which values they should have.

**Comment by ahornung** [comment]
Which bounds would that be exactly?

**Comment by jvgomez** [comment]
As you said before, `sensor_model_hit` >= 0.5 and `sensor_model_miss`<= 0.5. But what is an appropriate upper bound for `sensor_model_hit` and lower bound for  `sensor_model_miss`? The PR contains 1.0 and 0.0 respectively, but as far as I understand they can be +-infty.

**Comment by ahornung** [comment]
Ah, now I understand. All sensor model parameters are probabilities and must be within (0,1). They will be converted to log-odds (in range +-infty) only after they are set.

However, since dividing by 0 or computing log(0) is not possible they must be within the open interval (0,1).

So:
- sensor_model_hit >= 0.5 and < 1
- sensor_model_miss > 0 and <= 0.5
- sensor_model_min/max >= 0.0 and <= 1.0 (exactly 0 and 1 means no clamping)

I believe there can be more unexpected behavior with hit=1.0 or miss=0.0, so in reality they should be and eps (0.000001 ?) smaller and larger.

**Comment by ahornung** [comment]
By the way, any idea about [this problem](https://github.com/OctoMap/octomap_mapping/pull/26), @jvgomez? Could it be related to dynamic_reconfigure?

**Comment by jvgomez** [comment]
Ok, I will modify the code to take into account those epsilons.

**Comment by ahornung** [comment]
From the feeback in OctoMap/octomap_mapping#26 I guess devel is ready for release now?

**Comment by jvgomez** [comment]
More testing would be welcome, for sure. At least for my use case I could not find any difference.

**Comment by ahornung** [comment]
Tested enough to warrant a release? The final syncs for Indigo an Jade are coming up on April 1st.

**Comment by jvgomez** [comment]
I haven´t tested anymore, sorry, didn´t have the time. But as I said, for my application (some kind of simple turtlebot-like mapping with RGBD-camera) it worked fine.

**Comment by ahornung** [comment]
Would you have time for a simple test (basic mapping, switching a few options) from the shadow-fixed repo in the next days as well? I can then push the release, but would need feedback in case there needs to be something fixed until April 1st. Otherwise Indigo and Jade would get a broken version as last update.

**Comment by jvgomez** [comment]
I will to get some time to to test using my application but changing the library source. Which repository do you mean?

**Comment by tfoote** [comment]
The testing repository is documented here: http://wiki.ros.org/ShadowRepository packages get staged there between when a maintainer makes a release and they are built before they are pushed publicly.

**Comment by ahornung** [comment]
@jvgomez The new version 0.6.0 of octomap_mapping is now in the testing repository. So when you proceed as described in the link Tully posted, you can install it on your system. Your application then needs to be rebuilt against this new binary version for testing.

**Comment by jvgomez** [comment]
@ahornung I have followed those instructions and everything seems to work as it was working before. I have changed some options, added/removed obstacles, etc. In any case, it would be nice if we can find somebody else that can test it in their applications.

**Comment by ahornung** [comment]
Thanks for testing! Given that the changes were discussed and actively used in the devel branch I think that's OK.
